package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'BuildConf'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("BuildConf")
    name = "build conf"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        maven {
            name = "mvn tst"
            goals = "clean test"
        }
    }
}))

